<?php

namespace AppBundle\Repository;

/**
 * ComptetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
