# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\User: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
        #main:
        #    entity: { class: MyNamespace\MyBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern: ^/login$
        #    security: false

        main :
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
          #  pattern: ^/
          #  form_login:
          #      login_path: login
          #      check_path: login_check
          #  anonymous: true

            logout:
                path: /logout
                target: /

            remember_me:
                secret: "%secret%"
                lifetime: 2232000

  #  access_control:
  #    - { path: ^/admin, roles: ROLE_ADMIN }
  #    - { path : ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  #      - { path: ^/private/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  #      - { path: ^/private, roles: ROLE_ADMIN }
  #      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #main:
        #    anonymous: ~
        #    entity: { class: src\AppBundle\Entity\User, property: username }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
